/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dm_chatclient_ChatClient */

#ifndef _Included_dm_chatclient_ChatClient
 #define _Included_dm_chatclient_ChatClient
 #ifdef __cplusplus
extern "C" {
 #endif
/*
 * Class:     dm_chatclient_ChatClient
 * Method:    createClientNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dm_chatclient_ChatClient_createClientNative
    (JNIEnv*, jobject);

/*
 * Class:     dm_chatclient_ChatClient
 * Method:    setServerPropertiesNative
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_ChatClient_setServerPropertiesNative
    (JNIEnv*, jobject, jlong, jstring, jint);

/*
 * Class:     dm_chatclient_ChatClient
 * Method:    loginNative
 * Signature: (JLjava/lang/String;Ljava/lang/String)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_ChatClient_loginNative
    (JNIEnv*, jobject, jlong, jstring, jstring);

/*
 * Class:     dm_chatclient_ChatClient
 * Method:    disconnectNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_ChatClient_disconnectNative
    (JNIEnv*, jobject, jlong);

/*
 * Class:     dm_chatclient_ChatClient
 * Method:    sendMessageNative
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_ChatClient_sendMessageNative
    (JNIEnv*, jobject, jlong, jstring);

/*
 * Class:     dm_chatclient_ChatClient
 * Method:    destroyClientNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_ChatClient_destroyClientNative
    (JNIEnv*, jobject, jlong);

 #ifdef __cplusplus
}
 #endif
#endif
