/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dm_chatclient_chatclient_notifier_JNIChatClientNotifier */

#ifndef _Included_dm_chatclient_chatclient_notifier_JNIChatClientNotifier
#define _Included_dm_chatclient_chatclient_notifier_JNIChatClientNotifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dm_chatclient_chatclient_notifier_JNIChatClientNotifier
 * Method:    createNativeJNIListener
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dm_chatclient_chatclient_notifier_JNIChatClientNotifier_createNativeJNIListener
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dm_chatclient_chatclient_notifier_JNIChatClientNotifier
 * Method:    destroyNativeJNIListener
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_notifier_JNIChatClientNotifier_destroyNativeJNIListener
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
