/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dm_chatclient_chatclient_ChatClientJNIProxy */

#ifndef _Included_dm_chatclient_chatclient_ChatClientJNIProxy
#define _Included_dm_chatclient_chatclient_ChatClientJNIProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    createClientNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_createClientNative
  (JNIEnv *, jobject);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    connectNative
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_connectNative
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    loginNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_loginNative
  (JNIEnv *, jobject, jlong, jstring, jstring,jint);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    disconnectNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_disconnectNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    sendMessageNative
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_sendMessageNative
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    destroyClientNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_destroyClientNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    requestContactsNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_requestContactsNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    addListenerNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_addListenerNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    removeListenerNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_removeListenerNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    removeContactNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_removeContactNative
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     dm_chatclient_chatclient_ChatClientJNIProxy
 * Method:    addContactNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_ChatClientJNIProxy_addContactNative
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
