/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy */

#ifndef _Included_dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy
#define _Included_dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy
 * Method:    createNativeNotifierProxy
 * Signature: (Ldm/chatclient/chatclient/notifier/JNIChatClientNotifier;)J
 */
JNIEXPORT jlong JNICALL Java_dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy_createNativeNotifierProxy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy
 * Method:    setCallbackMethodNative
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy_setCallbackMethodNative
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy
 * Method:    destroyNativeNotifierProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dm_chatclient_chatclient_notifier_JNIChatClientNotifierProxy_destroyNativeNotifierProxy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
